### ISSUE TITLE
SSO پشتیبانی ?

### ISSUE THREAD

**Issue by KAJOOSH** [VahidN/ASPNETCore2CookieAuthentication#3]
آیا از این پروژه می توان احرازهویت SSO انجام داد ؟
یعنی چند سیستم داشته باشیم و یک سیستم احرازهویت مرکزی ؟

**Comment by VahidN** [comment]
خير. اينكار [مفصل‌تر از اين حرف‌ها](https://www.dntips.ir/learningpaths/details/75) است. براي اينكار بهتر است از [openiddict]( https://kevinchalet.com/2022/12/16/getting-started-with-the-openiddict-web-providers) استفاده كنيد.
